### ISSUE TITLE
add opengraph tags for sharing posts on social media

### ISSUE THREAD

**Issue by benloks** [Shuvayatra/shuvayatra-pwa#30]
@tyohan can you please help with this, if needed? We need to add tags for the title, description, and image so that we can share posts on Facebook or other social media

**Comment by tyohan** [comment]
@benloks been trying to go around on this issue. It's a same one with https://github.com/Shuvayatra/shuvayatra-pwa/issues/29 and base on my research dynamic single page app like this will not able to read by Facebook crawler. On best shot for this so far keep use the AMP page. Currently our AMP doesn't work because change on API. Will try to fix that.
